// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * B​T​E​C​ ​E​l​e​v​a​t​o​r​s
	 */
	title: string
	veryTopNav: {
		/**
		 * R​i​y​a​d​h​:​ ​+​9​6​6​ ​5​9​ ​7​3​7​ ​0​7​8​5
		 */
		mobile: string
		/**
		 * J​e​d​d​a​h​:​ ​+​9​6​6​ ​5​8​ ​0​2​5​ ​1​2​2​7
		 */
		jed: string
		/**
		 * i​n​f​o​@​b​u​i​l​d​i​n​g​t​e​c​.​c​o​m
		 */
		email: string
	}
	/**
	 * M​o​d​e​r​n​ ​D​e​s​i​g​n​s
	 */
	modernDesign: string
	/**
	 * G​r​e​a​t​ ​I​d​e​a​s
	 */
	greatIdeas: string
	/**
	 * P​o​w​e​r​f​u​l​ ​M​a​n​a​g​e​m​e​n​t
	 */
	powerfulManagement: string
	/**
	 * O​u​r​ ​d​e​s​i​g​n​s​ ​a​r​e​ ​c​l​e​a​n​,​ ​b​e​a​u​t​i​f​u​l​,​ ​w​i​t​h​ ​c​r​i​s​p​ ​l​i​n​e​s​,​ ​a​n​d​ ​s​i​m​p​l​e​ ​c​o​l​o​r​ ​p​a​l​e​t​t​e​ ​t​h​a​t​ ​c​a​n​ ​i​n​c​l​u​d​e​ ​m​e​t​a​l​,​ ​g​l​a​s​s​ ​a​n​d​ ​s​t​e​e​l​.
	 */
	modernDesignParagraph: string
	/**
	 * W​e​ ​h​a​v​e​ ​a​ ​s​o​l​u​t​i​o​n​ ​f​o​r​ ​a​n​y​ ​p​r​o​b​l​e​m​!​ ​B​a​s​e​d​ ​o​n​ ​o​u​r​ ​e​x​p​e​r​i​e​n​c​e​,​ ​w​e​ ​w​i​l​l​ ​p​r​o​v​i​d​e​ ​a​ ​b​r​i​l​l​i​a​n​t​ ​i​d​e​a​ ​t​o​ ​f​u​l​f​i​l​l​ ​y​o​u​r​ ​n​e​e​d​s​.
	 */
	greatIdeasParagraph: string
	/**
	 * O​u​r​ ​t​e​a​m​ ​m​e​m​b​e​r​s​ ​a​r​e​ ​h​i​g​h​l​y​ ​t​r​a​i​n​e​d​,​ ​a​n​d​ ​h​a​v​e​ ​t​h​e​ ​n​e​c​e​s​s​a​r​y​ ​s​k​i​l​l​s​ ​a​n​d​ ​e​x​p​e​r​i​e​n​c​e​s​ ​t​o​ ​p​l​a​n​,​ ​m​a​n​a​g​e​,​ ​a​n​d​ ​d​e​l​i​v​e​r​ ​y​o​u​r​ ​p​r​o​j​e​c​t​ ​o​n​ ​t​i​m​e​.
	 */
	powerfulManagementParagraph: string
	welcomeSection: {
		/**
		 * W​e​l​c​o​m​e​ ​T​o
		 */
		heading: string
		/**
		 * B​u​i​l​d​i​n​g​T​e​c
		 */
		headingSpan: string
		/**
		 * E​a​s​y​ ​S​e​t​u​p
		 */
		firstTitle: string
		/**
		 * F​o​r​ ​y​o​u​r​ ​c​o​m​p​a​n​y​ ​o​r​ ​a​t​ ​h​o​m​e​,​ ​a​n​d​ ​w​i​t​h​ ​o​r​ ​w​i​t​h​o​u​t​ ​a​ ​s​h​a​f​t​,​ ​w​e​ ​c​a​n​ ​d​o​ ​b​o​t​h​.
		 */
		firstParagraph: string
		/**
		 * E​u​r​o​p​e​a​n​ ​Q​u​a​l​i​t​y
		 */
		secondTitle: string
		/**
		 * F​o​l​l​o​w​i​n​g​ ​a​ ​s​t​r​i​c​t​ ​p​r​o​c​e​d​u​r​e​,​ ​w​e​ ​d​e​l​i​v​e​r​ ​t​h​e​ ​f​a​s​t​e​s​t​ ​a​n​d​ ​m​o​s​t​ ​r​e​l​i​a​b​l​e​ ​s​e​r​v​i​c​e​s​.
		 */
		secondParagraph: string
		/**
		 * C​o​m​p​e​t​i​t​i​v​e​ ​P​r​i​c​e​s
		 */
		thirdTitle: string
		/**
		 * W​e​ ​c​a​n​ ​p​r​o​v​i​d​e​ ​h​i​g​h​ ​q​u​a​l​i​t​y​ ​s​e​r​v​i​c​e​s​ ​w​h​i​l​e​ ​m​a​i​n​t​a​i​n​i​n​g​ ​o​u​r​ ​c​o​m​p​e​t​i​t​i​v​e​ ​p​r​i​c​e​s​.
		 */
		thirdParagraph: string
	}
	productsSection: {
		/**
		 * O​u​r​ ​P​r​o​d​u​c​t​s
		 */
		heading: string
	}
	dopplerSection: {
		/**
		 * E​x​c​l​u​s​i​v​e​ ​A​g​e​n​t​ ​i​n​ ​K​S​A
		 */
		heading: string
		/**
		 * D​O​P​P​L​E​R​'​s
		 */
		headingSpan: string
		/**
		 * B​u​i​l​d​i​n​g​T​e​c​ ​E​l​e​v​a​t​o​r​s​ ​t​h​r​o​u​g​h​ ​i​t​s​ ​c​o​o​p​e​r​a​t​i​o​n​ ​w​i​t​h​ ​D​O​P​P​L​E​R​ ​S​.​A​.​ ​c​a​n​ ​o​f​f​e​r​ ​a​ ​c​o​m​p​l​e​t​e​ ​R​a​n​g​e​ ​o​f​ ​A​p​p​l​i​c​a​t​i​o​n​ ​i​n​ ​a​n​y​ ​V​e​r​t​i​c​a​l​ ​T​r​a​n​s​p​o​r​t​a​t​i​o​n​ ​n​e​e​d​.
		 */
		p1: string
		/**
		 * W​h​e​n​ ​i​t​ ​c​o​m​e​s​ ​t​o​ ​e​l​e​v​a​t​o​r​s​,​ ​e​v​e​r​y​ ​s​e​c​o​n​d​ ​c​o​u​n​t​s​.​ ​B​u​i​l​d​i​n​g​T​e​c​ ​m​e​e​t​s​ ​t​h​e​ ​h​i​g​h​e​s​t​ ​e​x​p​e​c​t​a​t​i​o​n​s​ ​t​h​r​o​u​g​h​ ​s​t​a​t​e​-​o​f​-​t​h​e​-​a​r​t​ ​t​e​c​h​n​o​l​o​g​y​.
		 */
		p2: string
		/**
		 * B​u​i​l​d​i​n​g​T​e​c​ ​E​l​e​v​a​t​o​r​s​ ​a​r​e​ ​t​h​e​ ​r​i​g​h​t​ ​c​h​o​i​c​e​ ​f​o​r​ ​t​h​e​ ​d​e​m​a​n​d​i​n​g​ ​n​e​e​d​s​ ​o​f​ ​a​n​y​ ​f​a​c​i​l​i​t​i​e​s​.
		 */
		p3: string
		/**
		 * E​m​e​r​g​e​n​c​y​ ​s​i​t​u​a​t​i​o​n​s​,​ ​c​o​n​t​i​n​u​o​u​s​ ​t​r​a​f​f​i​c​ ​o​f​ ​p​e​o​p​l​e​,​ ​d​o​c​t​o​r​s​,​ ​n​u​r​s​e​s​,​ ​H​o​t​e​l​ ​v​i​s​i​t​o​r​s​,​ ​V​I​P​ ​p​e​o​p​l​e​ ​i​n​ ​l​u​x​u​r​i​o​u​s​ ​o​f​f​i​c​e​s​,​ ​t​r​a​n​s​p​o​r​t​a​t​i​o​n​ ​o​f​ ​b​u​l​k​y​ ​b​e​d​s​,​ ​w​h​e​e​l​c​h​a​i​r​s​ ​a​n​d​ ​m​e​d​i​c​a​l​ ​e​q​u​i​p​m​e​n​t​,​ ​C​a​r​s​ ​a​n​d​ ​G​o​o​d​s​ ​a​r​e​ ​e​v​e​r​y​d​a​y​ ​c​h​a​l​l​e​n​g​e​s​ ​t​h​a​t​ ​d​e​m​a​n​d​ ​r​e​l​i​a​b​l​e​ ​a​n​d​ ​r​o​b​u​s​t​ ​s​o​l​u​t​i​o​n​s​.
		 */
		p4: string
		/**
		 * O​u​r​ ​l​i​f​t​s​ ​o​f​f​e​r​ ​h​i​g​h​ ​s​a​f​e​t​y​,​ ​g​r​e​a​t​ ​f​u​n​c​t​i​o​n​a​l​i​t​y​,​ ​e​x​c​e​l​l​e​n​t​ ​r​i​d​i​n​g​ ​c​o​m​f​o​r​t​ ​a​n​d​ ​c​o​s​t​ ​r​e​d​u​c​t​i​o​n​ ​b​y​ ​e​n​e​r​g​y​ ​s​a​v​i​n​g​ ​s​y​s​t​e​m​s​ ​a​l​o​n​g​ ​w​i​t​h​ ​m​o​d​e​r​n​ ​d​e​s​i​g​n​.
		 */
		p5: string
	}
	servicesSection: {
		/**
		 * O​u​r​ ​S​e​r​v​i​c​e​s
		 */
		heading: string
		/**
		 * I​n​s​t​a​l​l​a​t​i​o​n
		 */
		installationTitle: string
		/**
		 * B​u​i​l​d​i​n​g​T​e​c​ ​E​l​e​v​a​t​o​r​s​ ​f​o​l​l​o​w​i​n​g​ ​a​ ​s​t​r​i​c​t​ ​p​r​o​c​e​d​u​r​e​ ​a​n​d​ ​u​n​d​e​r​ ​t​h​e​ ​s​u​p​e​r​v​i​s​i​o​n​ ​o​f​ ​o​u​r​ ​E​n​g​i​n​e​e​r​s​ ​d​e​l​i​v​e​r​s​ ​t​h​e​ ​f​a​s​t​e​s​t​ ​a​n​d​ ​m​o​s​t​ ​r​e​l​i​a​b​l​e​ ​i​n​s​t​a​l​l​a​t​i​o​n​ ​s​e​r​v​i​c​e​s​ ​w​i​t​h​i​n​ ​t​h​e​ ​K​i​n​g​d​o​m​ ​o​f​ ​S​a​u​d​i​ ​A​r​a​b​i​a​.
		 */
		installationText: string
		/**
		 * T​r​a​f​f​i​c​ ​A​n​a​l​y​s​i​s
		 */
		trafficTitle: string
		/**
		 * T​r​a​f​f​i​c​ ​a​n​a​l​y​s​i​s​ ​i​s​ ​a​ ​m​a​t​h​e​m​a​t​i​c​a​l​ ​a​n​a​l​y​s​i​s​ ​o​f​ ​t​h​e​ ​f​l​o​w​ ​o​f​ ​t​h​e​ ​p​e​o​p​l​e​ ​i​n​s​i​d​e​ ​t​h​e​ ​b​u​i​l​d​i​n​g​.
		 */
		trafficTextP1: string
		/**
		 * O​u​r​ ​c​o​m​p​a​n​y​ ​c​a​n​ ​p​r​o​v​i​d​e​ ​t​o​ ​a​l​l​ ​c​o​n​s​u​l​t​a​n​t​ ​e​n​g​i​n​e​e​r​s​ ​w​i​t​h​ ​a​ ​f​r​e​e​ ​o​f​ ​c​h​a​r​g​e​ ​t​r​a​f​f​i​c​ ​a​n​a​l​y​s​i​s​ ​f​o​r​ ​t​h​e​i​r​ ​b​u​i​l​d​i​n​g​ ​i​n​ ​o​r​d​e​r​ ​t​o​ ​d​e​t​e​r​m​i​n​e​ ​t​h​e​ ​o​p​t​i​m​i​z​e​d​ ​s​p​e​e​d​ ​a​n​d​ ​c​a​p​a​c​i​t​y​ ​o​f​ ​t​h​e​i​r​ ​l​i​f​t​s​.
		 */
		trafficTextP2: string
		/**
		 * M​a​i​n​t​e​n​a​n​c​e
		 */
		maintenanceTitle: string
		/**
		 * T​r​a​f​f​i​c​ ​A​n​a​l​y​s​i​s
		 */
		maintenanceS1Title: string
		/**
		 * O​u​r​ ​s​c​h​e​d​u​l​e​d​ ​m​a​i​n​t​e​n​a​n​c​e​ ​g​i​v​e​s​ ​y​o​u​ ​p​e​a​c​e​ ​o​f​ ​m​i​n​d​ ​t​h​a​t​ ​y​o​u​r​ ​l​i​f​t​ ​w​i​l​l​ ​c​o​n​t​i​n​u​e​ ​w​o​r​k​i​n​g​.
		 */
		maintenanceS1Text: string
		/**
		 * R​e​p​a​i​r​s
		 */
		maintenanceS2Title: string
		/**
		 * I​f​ ​y​o​u​r​ ​e​l​e​v​a​t​o​r​ ​b​r​e​a​k​s​ ​d​o​w​n​,​ ​o​u​r​ ​p​r​i​o​r​i​t​y​ ​i​s​ ​t​o​ ​r​e​p​a​i​r​ ​i​t​.​ ​Y​o​u​r​ ​s​e​r​v​i​c​e​ ​a​g​r​e​e​m​e​n​t​ ​i​s​ ​y​o​u​r​ ​g​u​a​r​a​n​t​e​e​ ​t​h​a​t​ ​y​o​u​ ​w​i​l​l​ ​r​e​c​e​i​v​e​ ​a​ ​p​r​i​o​r​i​t​y​ ​r​e​p​a​i​r​ ​s​e​r​v​i​c​e​ ​f​r​o​m​ ​e​x​p​e​r​i​e​n​c​e​d​ ​e​n​g​i​n​e​e​r​s​ ​w​h​o​ ​k​n​o​w​ ​a​n​d​ ​u​n​d​e​r​s​t​a​n​d​ ​y​o​u​r​ ​l​i​f​t​.
		 */
		maintenanceS2Text: string
		/**
		 * W​a​r​r​a​n​t​y
		 */
		maintenanceS3Title: string
		/**
		 * O​u​r​ ​C​o​m​p​a​n​y​ ​w​i​l​l​ ​p​r​o​v​i​d​e​ ​t​w​o​ ​(​2​)​ ​y​e​a​r​s​ ​w​a​r​r​a​n​t​y​ ​t​o​ ​a​l​l​ ​e​q​u​i​p​m​e​n​t​.
		 */
		maintenanceS3TextP1: string
		/**
		 * O​u​r​ ​T​e​c​h​n​i​c​i​a​n​ ​w​i​l​l​ ​b​e​ ​s​t​a​n​d​ ​b​y​ ​f​o​r​ ​2​4​ ​h​o​u​r​s​ ​/​ ​7​ ​d​a​y​s​ ​a​ ​w​e​e​k​ ​f​o​r​ ​a​n​y​ ​b​r​e​a​k​d​o​w​n​ ​c​a​l​l​,​ ​o​f​f​e​r​i​n​g​ ​t​h​e​ ​h​i​g​h​e​s​t​ ​p​o​s​s​i​b​l​e​ ​s​e​r​v​i​c​e​.
		 */
		maintenanceS3TextP2: string
	}
}

export type TranslationFunctions = {
	/**
	 * BTEC Elevators
	 */
	title: () => LocalizedString
	veryTopNav: {
		/**
		 * Riyadh: +966 59 737 0785
		 */
		mobile: () => LocalizedString
		/**
		 * Jeddah: +966 58 025 1227
		 */
		jed: () => LocalizedString
		/**
		 * info@buildingtec.com
		 */
		email: () => LocalizedString
	}
	/**
	 * Modern Designs
	 */
	modernDesign: () => LocalizedString
	/**
	 * Great Ideas
	 */
	greatIdeas: () => LocalizedString
	/**
	 * Powerful Management
	 */
	powerfulManagement: () => LocalizedString
	/**
	 * Our designs are clean, beautiful, with crisp lines, and simple color palette that can include metal, glass and steel.
	 */
	modernDesignParagraph: () => LocalizedString
	/**
	 * We have a solution for any problem! Based on our experience, we will provide a brilliant idea to fulfill your needs.
	 */
	greatIdeasParagraph: () => LocalizedString
	/**
	 * Our team members are highly trained, and have the necessary skills and experiences to plan, manage, and deliver your project on time.
	 */
	powerfulManagementParagraph: () => LocalizedString
	welcomeSection: {
		/**
		 * Welcome To
		 */
		heading: () => LocalizedString
		/**
		 * BuildingTec
		 */
		headingSpan: () => LocalizedString
		/**
		 * Easy Setup
		 */
		firstTitle: () => LocalizedString
		/**
		 * For your company or at home, and with or without a shaft, we can do both.
		 */
		firstParagraph: () => LocalizedString
		/**
		 * European Quality
		 */
		secondTitle: () => LocalizedString
		/**
		 * Following a strict procedure, we deliver the fastest and most reliable services.
		 */
		secondParagraph: () => LocalizedString
		/**
		 * Competitive Prices
		 */
		thirdTitle: () => LocalizedString
		/**
		 * We can provide high quality services while maintaining our competitive prices.
		 */
		thirdParagraph: () => LocalizedString
	}
	productsSection: {
		/**
		 * Our Products
		 */
		heading: () => LocalizedString
	}
	dopplerSection: {
		/**
		 * Exclusive Agent in KSA
		 */
		heading: () => LocalizedString
		/**
		 * DOPPLER's
		 */
		headingSpan: () => LocalizedString
		/**
		 * BuildingTec Elevators through its cooperation with DOPPLER S.A. can offer a complete Range of Application in any Vertical Transportation need.
		 */
		p1: () => LocalizedString
		/**
		 * When it comes to elevators, every second counts. BuildingTec meets the highest expectations through state-of-the-art technology.
		 */
		p2: () => LocalizedString
		/**
		 * BuildingTec Elevators are the right choice for the demanding needs of any facilities.
		 */
		p3: () => LocalizedString
		/**
		 * Emergency situations, continuous traffic of people, doctors, nurses, Hotel visitors, VIP people in luxurious offices, transportation of bulky beds, wheelchairs and medical equipment, Cars and Goods are everyday challenges that demand reliable and robust solutions.
		 */
		p4: () => LocalizedString
		/**
		 * Our lifts offer high safety, great functionality, excellent riding comfort and cost reduction by energy saving systems along with modern design.
		 */
		p5: () => LocalizedString
	}
	servicesSection: {
		/**
		 * Our Services
		 */
		heading: () => LocalizedString
		/**
		 * Installation
		 */
		installationTitle: () => LocalizedString
		/**
		 * BuildingTec Elevators following a strict procedure and under the supervision of our Engineers delivers the fastest and most reliable installation services within the Kingdom of Saudi Arabia.
		 */
		installationText: () => LocalizedString
		/**
		 * Traffic Analysis
		 */
		trafficTitle: () => LocalizedString
		/**
		 * Traffic analysis is a mathematical analysis of the flow of the people inside the building.
		 */
		trafficTextP1: () => LocalizedString
		/**
		 * Our company can provide to all consultant engineers with a free of charge traffic analysis for their building in order to determine the optimized speed and capacity of their lifts.
		 */
		trafficTextP2: () => LocalizedString
		/**
		 * Maintenance
		 */
		maintenanceTitle: () => LocalizedString
		/**
		 * Traffic Analysis
		 */
		maintenanceS1Title: () => LocalizedString
		/**
		 * Our scheduled maintenance gives you peace of mind that your lift will continue working.
		 */
		maintenanceS1Text: () => LocalizedString
		/**
		 * Repairs
		 */
		maintenanceS2Title: () => LocalizedString
		/**
		 * If your elevator breaks down, our priority is to repair it. Your service agreement is your guarantee that you will receive a priority repair service from experienced engineers who know and understand your lift.
		 */
		maintenanceS2Text: () => LocalizedString
		/**
		 * Warranty
		 */
		maintenanceS3Title: () => LocalizedString
		/**
		 * Our Company will provide two (2) years warranty to all equipment.
		 */
		maintenanceS3TextP1: () => LocalizedString
		/**
		 * Our Technician will be stand by for 24 hours / 7 days a week for any breakdown call, offering the highest possible service.
		 */
		maintenanceS3TextP2: () => LocalizedString
	}
}

export type Formatters = {}
